services:
  postgres_ja:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "defaultPassword"
    ports:
      - "5142:5432"
    container_name: postgres_ja
